export const COLORS = {
  PRIMARY: "#E91E63",

  LIGHT: {
    TEXT_PRIMARY: "#000000",
    TEXT_SECONDARY: "#333333",
    BACKGROUND: "#FFFFFF",
    PAPER: "#F5F5F5",
  },

  DARK: {
    TEXT_PRIMARY: "#FFFFFF",
    TEXT_SECONDARY: "#EEEEEE",
    BACKGROUND: "#121212",
    PAPER: "#1E1E1E",
  },
};
